# Generated by Django 4.0.5 on 2022-07-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('obj', models.CharField(max_length=10, verbose_name='model')),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
