# Generated by Django 4.0.5 on 2022-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
